source 'https://github.com/CocoaPods/Specs.git'

target 'SVSwipeView', :exclusive => true do
  pod "SVSwipeView", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "SVSwipeView", :path => "../"

  pod 'FBSnapshotTestCase'
end
